name: example
description: "FFMPEG example"
publish_to: 'none'

version: 1.0.0+1

# environment:
#   sdk: ^3.7.2
environment:
  sdk: '>=3.8.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  # ffmpeg_kit_flutter_new:
  #   path: ../
  ffmpeg_kit_flutter_new: ^3.1.0
  permission_handler: ^12.0.1
  gal: ^2.3.2
  fluttertoast: ^8.2.12
  video_player: ^2.10.0
  flutter_vlc_player: ^7.4.3
  # rtsp_ffmpeg:
  #   path: C:/Users/User/Desktop/ffmpeg_kit_flutter_example/dep/flutter_rtsp_videoplayer_2222

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/